[package]
name = "vertis_fi"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }
starknet = "2.5.0"

[lib]
sierra = true

[[target.starknet-contract]]
casm = false
